session AutoCorrode = HOL +
  sessions
    "HOL-Eisbach"
    "HOL-Library"
    "Word_Lib"
    (* AutoCorrode specific *)
    "Autogen"
    "Parser_Common"
    "Byte_Level_Encoding"
    "Crush"
    "Data_Structures"
    "Enum_Theory"
    "Frontend_Common"
    "iq"
    "Language_Isolation_Tests"
    "Micro_C_Isabelle_C_Adapter"
    "Micro_C_Parser_Tests"
    "Micro_C_Parsing_Frontend"
    "Micro_C_Examples"
    "Micro_Rust_Examples"
    "Micro_Rust_Interfaces"
    "Micro_Rust_Interfaces_Core"
    "Micro_Rust_Parser_Impl"
    "Micro_Rust_Runtime"
    "Micro_Rust_Std_Lib"
    "Misc"
    "Lenses_And_Other_Optics"
    "Separation_Lenses"
    "Shallow_Computation"
    "Shallow_Micro_C"
    "Shallow_Micro_Rust"
    "Shallow_State"
    "Shallow_State_Logic"
    "Shallow_Separation_Logic"
  theories [document = false]
    "AutoCorrode"
